/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkbookChartGridlines struct for WorkbookChartGridlines
type WorkbookChartGridlines struct {
	// Boolean value representing if the axis gridlines are visible or not.
	Visible *bool `json:"visible,omitempty"`
	// Represents the formatting of chart gridlines. Read-only.
	Format AnyOfmicrosoftGraphWorkbookChartGridlinesFormat `json:"format,omitempty"`
}

// NewWorkbookChartGridlines instantiates a new WorkbookChartGridlines object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkbookChartGridlines() *WorkbookChartGridlines {
	this := WorkbookChartGridlines{}
	return &this
}

// NewWorkbookChartGridlinesWithDefaults instantiates a new WorkbookChartGridlines object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkbookChartGridlinesWithDefaults() *WorkbookChartGridlines {
	this := WorkbookChartGridlines{}
	return &this
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *WorkbookChartGridlines) GetVisible() bool {
	if o == nil || o.Visible == nil {
		var ret bool
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkbookChartGridlines) GetVisibleOk() (*bool, bool) {
	if o == nil || o.Visible == nil {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *WorkbookChartGridlines) HasVisible() bool {
	if o != nil && o.Visible != nil {
		return true
	}

	return false
}

// SetVisible gets a reference to the given bool and assigns it to the Visible field.
func (o *WorkbookChartGridlines) SetVisible(v bool) {
	o.Visible = &v
}

// GetFormat returns the Format field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkbookChartGridlines) GetFormat() AnyOfmicrosoftGraphWorkbookChartGridlinesFormat {
	if o == nil  {
		var ret AnyOfmicrosoftGraphWorkbookChartGridlinesFormat
		return ret
	}
	return o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkbookChartGridlines) GetFormatOk() (*AnyOfmicrosoftGraphWorkbookChartGridlinesFormat, bool) {
	if o == nil || o.Format == nil {
		return nil, false
	}
	return &o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *WorkbookChartGridlines) HasFormat() bool {
	if o != nil && o.Format != nil {
		return true
	}

	return false
}

// SetFormat gets a reference to the given AnyOfmicrosoftGraphWorkbookChartGridlinesFormat and assigns it to the Format field.
func (o *WorkbookChartGridlines) SetFormat(v AnyOfmicrosoftGraphWorkbookChartGridlinesFormat) {
	o.Format = v
}

func (o WorkbookChartGridlines) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Visible != nil {
		toSerialize["visible"] = o.Visible
	}
	if o.Format != nil {
		toSerialize["format"] = o.Format
	}
	return json.Marshal(toSerialize)
}

type NullableWorkbookChartGridlines struct {
	value *WorkbookChartGridlines
	isSet bool
}

func (v NullableWorkbookChartGridlines) Get() *WorkbookChartGridlines {
	return v.value
}

func (v *NullableWorkbookChartGridlines) Set(val *WorkbookChartGridlines) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkbookChartGridlines) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkbookChartGridlines) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkbookChartGridlines(val *WorkbookChartGridlines) *NullableWorkbookChartGridlines {
	return &NullableWorkbookChartGridlines{value: val, isSet: true}
}

func (v NullableWorkbookChartGridlines) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkbookChartGridlines) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


