/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject554 struct for InlineObject554
type InlineObject554 struct {
	Shift *string `json:"shift,omitempty"`
}

// NewInlineObject554 instantiates a new InlineObject554 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject554() *InlineObject554 {
	this := InlineObject554{}
	return &this
}

// NewInlineObject554WithDefaults instantiates a new InlineObject554 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject554WithDefaults() *InlineObject554 {
	this := InlineObject554{}
	return &this
}

// GetShift returns the Shift field value if set, zero value otherwise.
func (o *InlineObject554) GetShift() string {
	if o == nil || o.Shift == nil {
		var ret string
		return ret
	}
	return *o.Shift
}

// GetShiftOk returns a tuple with the Shift field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject554) GetShiftOk() (*string, bool) {
	if o == nil || o.Shift == nil {
		return nil, false
	}
	return o.Shift, true
}

// HasShift returns a boolean if a field has been set.
func (o *InlineObject554) HasShift() bool {
	if o != nil && o.Shift != nil {
		return true
	}

	return false
}

// SetShift gets a reference to the given string and assigns it to the Shift field.
func (o *InlineObject554) SetShift(v string) {
	o.Shift = &v
}

func (o InlineObject554) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Shift != nil {
		toSerialize["shift"] = o.Shift
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject554 struct {
	value *InlineObject554
	isSet bool
}

func (v NullableInlineObject554) Get() *InlineObject554 {
	return v.value
}

func (v *NullableInlineObject554) Set(val *InlineObject554) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject554) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject554) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject554(val *InlineObject554) *NullableInlineObject554 {
	return &NullableInlineObject554{value: val, isSet: true}
}

func (v NullableInlineObject554) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject554) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


