/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// MicrosoftGraphSectionGroup struct for MicrosoftGraphSectionGroup
type MicrosoftGraphSectionGroup struct {
	// Read-only.
	Id *string `json:"id,omitempty"`
	// The endpoint where you can get details about the page. Read-only.
	Self NullableString `json:"self,omitempty"`
	// The date and time when the page was created. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.
	CreatedDateTime NullableTime `json:"createdDateTime,omitempty"`
	// Identity of the user, device, and application which created the item. Read-only.
	CreatedBy AnyOfmicrosoftGraphIdentitySet `json:"createdBy,omitempty"`
	// The name of the notebook.
	DisplayName NullableString `json:"displayName,omitempty"`
	// Identity of the user, device, and application which created the item. Read-only.
	LastModifiedBy AnyOfmicrosoftGraphIdentitySet `json:"lastModifiedBy,omitempty"`
	// The date and time when the notebook was last modified. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.
	LastModifiedDateTime NullableTime `json:"lastModifiedDateTime,omitempty"`
	// The URL for the sectionGroups navigation property, which returns all the section groups in the section group. Read-only.
	SectionGroupsUrl NullableString `json:"sectionGroupsUrl,omitempty"`
	// The URL for the sections navigation property, which returns all the sections in the section group. Read-only.
	SectionsUrl NullableString `json:"sectionsUrl,omitempty"`
	// The notebook that contains the section group. Read-only.
	ParentNotebook AnyOfmicrosoftGraphNotebook `json:"parentNotebook,omitempty"`
	// The section group that contains the section group. Read-only.
	ParentSectionGroup AnyOfmicrosoftGraphSectionGroup `json:"parentSectionGroup,omitempty"`
	// The section groups in the section. Read-only. Nullable.
	SectionGroups *[]MicrosoftGraphSectionGroup `json:"sectionGroups,omitempty"`
	// The sections in the section group. Read-only. Nullable.
	Sections *[]MicrosoftGraphOnenoteSection `json:"sections,omitempty"`
}

// NewMicrosoftGraphSectionGroup instantiates a new MicrosoftGraphSectionGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMicrosoftGraphSectionGroup() *MicrosoftGraphSectionGroup {
	this := MicrosoftGraphSectionGroup{}
	return &this
}

// NewMicrosoftGraphSectionGroupWithDefaults instantiates a new MicrosoftGraphSectionGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMicrosoftGraphSectionGroupWithDefaults() *MicrosoftGraphSectionGroup {
	this := MicrosoftGraphSectionGroup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MicrosoftGraphSectionGroup) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphSectionGroup) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MicrosoftGraphSectionGroup) SetId(v string) {
	o.Id = &v
}

// GetSelf returns the Self field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetSelf() string {
	if o == nil || o.Self.Get() == nil {
		var ret string
		return ret
	}
	return *o.Self.Get()
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetSelfOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Self.Get(), o.Self.IsSet()
}

// HasSelf returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasSelf() bool {
	if o != nil && o.Self.IsSet() {
		return true
	}

	return false
}

// SetSelf gets a reference to the given NullableString and assigns it to the Self field.
func (o *MicrosoftGraphSectionGroup) SetSelf(v string) {
	o.Self.Set(&v)
}
// SetSelfNil sets the value for Self to be an explicit nil
func (o *MicrosoftGraphSectionGroup) SetSelfNil() {
	o.Self.Set(nil)
}

// UnsetSelf ensures that no value is present for Self, not even an explicit nil
func (o *MicrosoftGraphSectionGroup) UnsetSelf() {
	o.Self.Unset()
}

// GetCreatedDateTime returns the CreatedDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetCreatedDateTime() time.Time {
	if o == nil || o.CreatedDateTime.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedDateTime.Get()
}

// GetCreatedDateTimeOk returns a tuple with the CreatedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetCreatedDateTimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CreatedDateTime.Get(), o.CreatedDateTime.IsSet()
}

// HasCreatedDateTime returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasCreatedDateTime() bool {
	if o != nil && o.CreatedDateTime.IsSet() {
		return true
	}

	return false
}

// SetCreatedDateTime gets a reference to the given NullableTime and assigns it to the CreatedDateTime field.
func (o *MicrosoftGraphSectionGroup) SetCreatedDateTime(v time.Time) {
	o.CreatedDateTime.Set(&v)
}
// SetCreatedDateTimeNil sets the value for CreatedDateTime to be an explicit nil
func (o *MicrosoftGraphSectionGroup) SetCreatedDateTimeNil() {
	o.CreatedDateTime.Set(nil)
}

// UnsetCreatedDateTime ensures that no value is present for CreatedDateTime, not even an explicit nil
func (o *MicrosoftGraphSectionGroup) UnsetCreatedDateTime() {
	o.CreatedDateTime.Unset()
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetCreatedBy() AnyOfmicrosoftGraphIdentitySet {
	if o == nil  {
		var ret AnyOfmicrosoftGraphIdentitySet
		return ret
	}
	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetCreatedByOk() (*AnyOfmicrosoftGraphIdentitySet, bool) {
	if o == nil || o.CreatedBy == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasCreatedBy() bool {
	if o != nil && o.CreatedBy != nil {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given AnyOfmicrosoftGraphIdentitySet and assigns it to the CreatedBy field.
func (o *MicrosoftGraphSectionGroup) SetCreatedBy(v AnyOfmicrosoftGraphIdentitySet) {
	o.CreatedBy = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetDisplayName() string {
	if o == nil || o.DisplayName.Get() == nil {
		var ret string
		return ret
	}
	return *o.DisplayName.Get()
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetDisplayNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DisplayName.Get(), o.DisplayName.IsSet()
}

// HasDisplayName returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasDisplayName() bool {
	if o != nil && o.DisplayName.IsSet() {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given NullableString and assigns it to the DisplayName field.
func (o *MicrosoftGraphSectionGroup) SetDisplayName(v string) {
	o.DisplayName.Set(&v)
}
// SetDisplayNameNil sets the value for DisplayName to be an explicit nil
func (o *MicrosoftGraphSectionGroup) SetDisplayNameNil() {
	o.DisplayName.Set(nil)
}

// UnsetDisplayName ensures that no value is present for DisplayName, not even an explicit nil
func (o *MicrosoftGraphSectionGroup) UnsetDisplayName() {
	o.DisplayName.Unset()
}

// GetLastModifiedBy returns the LastModifiedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetLastModifiedBy() AnyOfmicrosoftGraphIdentitySet {
	if o == nil  {
		var ret AnyOfmicrosoftGraphIdentitySet
		return ret
	}
	return o.LastModifiedBy
}

// GetLastModifiedByOk returns a tuple with the LastModifiedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetLastModifiedByOk() (*AnyOfmicrosoftGraphIdentitySet, bool) {
	if o == nil || o.LastModifiedBy == nil {
		return nil, false
	}
	return &o.LastModifiedBy, true
}

// HasLastModifiedBy returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasLastModifiedBy() bool {
	if o != nil && o.LastModifiedBy != nil {
		return true
	}

	return false
}

// SetLastModifiedBy gets a reference to the given AnyOfmicrosoftGraphIdentitySet and assigns it to the LastModifiedBy field.
func (o *MicrosoftGraphSectionGroup) SetLastModifiedBy(v AnyOfmicrosoftGraphIdentitySet) {
	o.LastModifiedBy = v
}

// GetLastModifiedDateTime returns the LastModifiedDateTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetLastModifiedDateTime() time.Time {
	if o == nil || o.LastModifiedDateTime.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.LastModifiedDateTime.Get()
}

// GetLastModifiedDateTimeOk returns a tuple with the LastModifiedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetLastModifiedDateTimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastModifiedDateTime.Get(), o.LastModifiedDateTime.IsSet()
}

// HasLastModifiedDateTime returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasLastModifiedDateTime() bool {
	if o != nil && o.LastModifiedDateTime.IsSet() {
		return true
	}

	return false
}

// SetLastModifiedDateTime gets a reference to the given NullableTime and assigns it to the LastModifiedDateTime field.
func (o *MicrosoftGraphSectionGroup) SetLastModifiedDateTime(v time.Time) {
	o.LastModifiedDateTime.Set(&v)
}
// SetLastModifiedDateTimeNil sets the value for LastModifiedDateTime to be an explicit nil
func (o *MicrosoftGraphSectionGroup) SetLastModifiedDateTimeNil() {
	o.LastModifiedDateTime.Set(nil)
}

// UnsetLastModifiedDateTime ensures that no value is present for LastModifiedDateTime, not even an explicit nil
func (o *MicrosoftGraphSectionGroup) UnsetLastModifiedDateTime() {
	o.LastModifiedDateTime.Unset()
}

// GetSectionGroupsUrl returns the SectionGroupsUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetSectionGroupsUrl() string {
	if o == nil || o.SectionGroupsUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.SectionGroupsUrl.Get()
}

// GetSectionGroupsUrlOk returns a tuple with the SectionGroupsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetSectionGroupsUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SectionGroupsUrl.Get(), o.SectionGroupsUrl.IsSet()
}

// HasSectionGroupsUrl returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasSectionGroupsUrl() bool {
	if o != nil && o.SectionGroupsUrl.IsSet() {
		return true
	}

	return false
}

// SetSectionGroupsUrl gets a reference to the given NullableString and assigns it to the SectionGroupsUrl field.
func (o *MicrosoftGraphSectionGroup) SetSectionGroupsUrl(v string) {
	o.SectionGroupsUrl.Set(&v)
}
// SetSectionGroupsUrlNil sets the value for SectionGroupsUrl to be an explicit nil
func (o *MicrosoftGraphSectionGroup) SetSectionGroupsUrlNil() {
	o.SectionGroupsUrl.Set(nil)
}

// UnsetSectionGroupsUrl ensures that no value is present for SectionGroupsUrl, not even an explicit nil
func (o *MicrosoftGraphSectionGroup) UnsetSectionGroupsUrl() {
	o.SectionGroupsUrl.Unset()
}

// GetSectionsUrl returns the SectionsUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetSectionsUrl() string {
	if o == nil || o.SectionsUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.SectionsUrl.Get()
}

// GetSectionsUrlOk returns a tuple with the SectionsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetSectionsUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SectionsUrl.Get(), o.SectionsUrl.IsSet()
}

// HasSectionsUrl returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasSectionsUrl() bool {
	if o != nil && o.SectionsUrl.IsSet() {
		return true
	}

	return false
}

// SetSectionsUrl gets a reference to the given NullableString and assigns it to the SectionsUrl field.
func (o *MicrosoftGraphSectionGroup) SetSectionsUrl(v string) {
	o.SectionsUrl.Set(&v)
}
// SetSectionsUrlNil sets the value for SectionsUrl to be an explicit nil
func (o *MicrosoftGraphSectionGroup) SetSectionsUrlNil() {
	o.SectionsUrl.Set(nil)
}

// UnsetSectionsUrl ensures that no value is present for SectionsUrl, not even an explicit nil
func (o *MicrosoftGraphSectionGroup) UnsetSectionsUrl() {
	o.SectionsUrl.Unset()
}

// GetParentNotebook returns the ParentNotebook field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetParentNotebook() AnyOfmicrosoftGraphNotebook {
	if o == nil  {
		var ret AnyOfmicrosoftGraphNotebook
		return ret
	}
	return o.ParentNotebook
}

// GetParentNotebookOk returns a tuple with the ParentNotebook field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetParentNotebookOk() (*AnyOfmicrosoftGraphNotebook, bool) {
	if o == nil || o.ParentNotebook == nil {
		return nil, false
	}
	return &o.ParentNotebook, true
}

// HasParentNotebook returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasParentNotebook() bool {
	if o != nil && o.ParentNotebook != nil {
		return true
	}

	return false
}

// SetParentNotebook gets a reference to the given AnyOfmicrosoftGraphNotebook and assigns it to the ParentNotebook field.
func (o *MicrosoftGraphSectionGroup) SetParentNotebook(v AnyOfmicrosoftGraphNotebook) {
	o.ParentNotebook = v
}

// GetParentSectionGroup returns the ParentSectionGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphSectionGroup) GetParentSectionGroup() AnyOfmicrosoftGraphSectionGroup {
	if o == nil  {
		var ret AnyOfmicrosoftGraphSectionGroup
		return ret
	}
	return o.ParentSectionGroup
}

// GetParentSectionGroupOk returns a tuple with the ParentSectionGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphSectionGroup) GetParentSectionGroupOk() (*AnyOfmicrosoftGraphSectionGroup, bool) {
	if o == nil || o.ParentSectionGroup == nil {
		return nil, false
	}
	return &o.ParentSectionGroup, true
}

// HasParentSectionGroup returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasParentSectionGroup() bool {
	if o != nil && o.ParentSectionGroup != nil {
		return true
	}

	return false
}

// SetParentSectionGroup gets a reference to the given AnyOfmicrosoftGraphSectionGroup and assigns it to the ParentSectionGroup field.
func (o *MicrosoftGraphSectionGroup) SetParentSectionGroup(v AnyOfmicrosoftGraphSectionGroup) {
	o.ParentSectionGroup = v
}

// GetSectionGroups returns the SectionGroups field value if set, zero value otherwise.
func (o *MicrosoftGraphSectionGroup) GetSectionGroups() []MicrosoftGraphSectionGroup {
	if o == nil || o.SectionGroups == nil {
		var ret []MicrosoftGraphSectionGroup
		return ret
	}
	return *o.SectionGroups
}

// GetSectionGroupsOk returns a tuple with the SectionGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphSectionGroup) GetSectionGroupsOk() (*[]MicrosoftGraphSectionGroup, bool) {
	if o == nil || o.SectionGroups == nil {
		return nil, false
	}
	return o.SectionGroups, true
}

// HasSectionGroups returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasSectionGroups() bool {
	if o != nil && o.SectionGroups != nil {
		return true
	}

	return false
}

// SetSectionGroups gets a reference to the given []MicrosoftGraphSectionGroup and assigns it to the SectionGroups field.
func (o *MicrosoftGraphSectionGroup) SetSectionGroups(v []MicrosoftGraphSectionGroup) {
	o.SectionGroups = &v
}

// GetSections returns the Sections field value if set, zero value otherwise.
func (o *MicrosoftGraphSectionGroup) GetSections() []MicrosoftGraphOnenoteSection {
	if o == nil || o.Sections == nil {
		var ret []MicrosoftGraphOnenoteSection
		return ret
	}
	return *o.Sections
}

// GetSectionsOk returns a tuple with the Sections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphSectionGroup) GetSectionsOk() (*[]MicrosoftGraphOnenoteSection, bool) {
	if o == nil || o.Sections == nil {
		return nil, false
	}
	return o.Sections, true
}

// HasSections returns a boolean if a field has been set.
func (o *MicrosoftGraphSectionGroup) HasSections() bool {
	if o != nil && o.Sections != nil {
		return true
	}

	return false
}

// SetSections gets a reference to the given []MicrosoftGraphOnenoteSection and assigns it to the Sections field.
func (o *MicrosoftGraphSectionGroup) SetSections(v []MicrosoftGraphOnenoteSection) {
	o.Sections = &v
}

func (o MicrosoftGraphSectionGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Self.IsSet() {
		toSerialize["self"] = o.Self.Get()
	}
	if o.CreatedDateTime.IsSet() {
		toSerialize["createdDateTime"] = o.CreatedDateTime.Get()
	}
	if o.CreatedBy != nil {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if o.DisplayName.IsSet() {
		toSerialize["displayName"] = o.DisplayName.Get()
	}
	if o.LastModifiedBy != nil {
		toSerialize["lastModifiedBy"] = o.LastModifiedBy
	}
	if o.LastModifiedDateTime.IsSet() {
		toSerialize["lastModifiedDateTime"] = o.LastModifiedDateTime.Get()
	}
	if o.SectionGroupsUrl.IsSet() {
		toSerialize["sectionGroupsUrl"] = o.SectionGroupsUrl.Get()
	}
	if o.SectionsUrl.IsSet() {
		toSerialize["sectionsUrl"] = o.SectionsUrl.Get()
	}
	if o.ParentNotebook != nil {
		toSerialize["parentNotebook"] = o.ParentNotebook
	}
	if o.ParentSectionGroup != nil {
		toSerialize["parentSectionGroup"] = o.ParentSectionGroup
	}
	if o.SectionGroups != nil {
		toSerialize["sectionGroups"] = o.SectionGroups
	}
	if o.Sections != nil {
		toSerialize["sections"] = o.Sections
	}
	return json.Marshal(toSerialize)
}

type NullableMicrosoftGraphSectionGroup struct {
	value *MicrosoftGraphSectionGroup
	isSet bool
}

func (v NullableMicrosoftGraphSectionGroup) Get() *MicrosoftGraphSectionGroup {
	return v.value
}

func (v *NullableMicrosoftGraphSectionGroup) Set(val *MicrosoftGraphSectionGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableMicrosoftGraphSectionGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableMicrosoftGraphSectionGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMicrosoftGraphSectionGroup(val *MicrosoftGraphSectionGroup) *NullableMicrosoftGraphSectionGroup {
	return &NullableMicrosoftGraphSectionGroup{value: val, isSet: true}
}

func (v NullableMicrosoftGraphSectionGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMicrosoftGraphSectionGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


