/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MicrosoftGraphTeamsAppInstallation struct for MicrosoftGraphTeamsAppInstallation
type MicrosoftGraphTeamsAppInstallation struct {
	// Read-only.
	Id *string `json:"id,omitempty"`
	// The app that is installed.
	TeamsApp AnyOfmicrosoftGraphTeamsApp `json:"teamsApp,omitempty"`
	// The details of this version of the app.
	TeamsAppDefinition AnyOfmicrosoftGraphTeamsAppDefinition `json:"teamsAppDefinition,omitempty"`
}

// NewMicrosoftGraphTeamsAppInstallation instantiates a new MicrosoftGraphTeamsAppInstallation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMicrosoftGraphTeamsAppInstallation() *MicrosoftGraphTeamsAppInstallation {
	this := MicrosoftGraphTeamsAppInstallation{}
	return &this
}

// NewMicrosoftGraphTeamsAppInstallationWithDefaults instantiates a new MicrosoftGraphTeamsAppInstallation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMicrosoftGraphTeamsAppInstallationWithDefaults() *MicrosoftGraphTeamsAppInstallation {
	this := MicrosoftGraphTeamsAppInstallation{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MicrosoftGraphTeamsAppInstallation) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphTeamsAppInstallation) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MicrosoftGraphTeamsAppInstallation) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MicrosoftGraphTeamsAppInstallation) SetId(v string) {
	o.Id = &v
}

// GetTeamsApp returns the TeamsApp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphTeamsAppInstallation) GetTeamsApp() AnyOfmicrosoftGraphTeamsApp {
	if o == nil  {
		var ret AnyOfmicrosoftGraphTeamsApp
		return ret
	}
	return o.TeamsApp
}

// GetTeamsAppOk returns a tuple with the TeamsApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphTeamsAppInstallation) GetTeamsAppOk() (*AnyOfmicrosoftGraphTeamsApp, bool) {
	if o == nil || o.TeamsApp == nil {
		return nil, false
	}
	return &o.TeamsApp, true
}

// HasTeamsApp returns a boolean if a field has been set.
func (o *MicrosoftGraphTeamsAppInstallation) HasTeamsApp() bool {
	if o != nil && o.TeamsApp != nil {
		return true
	}

	return false
}

// SetTeamsApp gets a reference to the given AnyOfmicrosoftGraphTeamsApp and assigns it to the TeamsApp field.
func (o *MicrosoftGraphTeamsAppInstallation) SetTeamsApp(v AnyOfmicrosoftGraphTeamsApp) {
	o.TeamsApp = v
}

// GetTeamsAppDefinition returns the TeamsAppDefinition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphTeamsAppInstallation) GetTeamsAppDefinition() AnyOfmicrosoftGraphTeamsAppDefinition {
	if o == nil  {
		var ret AnyOfmicrosoftGraphTeamsAppDefinition
		return ret
	}
	return o.TeamsAppDefinition
}

// GetTeamsAppDefinitionOk returns a tuple with the TeamsAppDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphTeamsAppInstallation) GetTeamsAppDefinitionOk() (*AnyOfmicrosoftGraphTeamsAppDefinition, bool) {
	if o == nil || o.TeamsAppDefinition == nil {
		return nil, false
	}
	return &o.TeamsAppDefinition, true
}

// HasTeamsAppDefinition returns a boolean if a field has been set.
func (o *MicrosoftGraphTeamsAppInstallation) HasTeamsAppDefinition() bool {
	if o != nil && o.TeamsAppDefinition != nil {
		return true
	}

	return false
}

// SetTeamsAppDefinition gets a reference to the given AnyOfmicrosoftGraphTeamsAppDefinition and assigns it to the TeamsAppDefinition field.
func (o *MicrosoftGraphTeamsAppInstallation) SetTeamsAppDefinition(v AnyOfmicrosoftGraphTeamsAppDefinition) {
	o.TeamsAppDefinition = v
}

func (o MicrosoftGraphTeamsAppInstallation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.TeamsApp != nil {
		toSerialize["teamsApp"] = o.TeamsApp
	}
	if o.TeamsAppDefinition != nil {
		toSerialize["teamsAppDefinition"] = o.TeamsAppDefinition
	}
	return json.Marshal(toSerialize)
}

type NullableMicrosoftGraphTeamsAppInstallation struct {
	value *MicrosoftGraphTeamsAppInstallation
	isSet bool
}

func (v NullableMicrosoftGraphTeamsAppInstallation) Get() *MicrosoftGraphTeamsAppInstallation {
	return v.value
}

func (v *NullableMicrosoftGraphTeamsAppInstallation) Set(val *MicrosoftGraphTeamsAppInstallation) {
	v.value = val
	v.isSet = true
}

func (v NullableMicrosoftGraphTeamsAppInstallation) IsSet() bool {
	return v.isSet
}

func (v *NullableMicrosoftGraphTeamsAppInstallation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMicrosoftGraphTeamsAppInstallation(val *MicrosoftGraphTeamsAppInstallation) *NullableMicrosoftGraphTeamsAppInstallation {
	return &NullableMicrosoftGraphTeamsAppInstallation{value: val, isSet: true}
}

func (v NullableMicrosoftGraphTeamsAppInstallation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMicrosoftGraphTeamsAppInstallation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


