/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CollectionOfExternalGroup struct for CollectionOfExternalGroup
type CollectionOfExternalGroup struct {
	Value *[]MicrosoftGraphExternalConnectorsExternalGroup `json:"value,omitempty"`
	OdataNextLink *string `json:"@odata.nextLink,omitempty"`
}

// NewCollectionOfExternalGroup instantiates a new CollectionOfExternalGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionOfExternalGroup() *CollectionOfExternalGroup {
	this := CollectionOfExternalGroup{}
	return &this
}

// NewCollectionOfExternalGroupWithDefaults instantiates a new CollectionOfExternalGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionOfExternalGroupWithDefaults() *CollectionOfExternalGroup {
	this := CollectionOfExternalGroup{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CollectionOfExternalGroup) GetValue() []MicrosoftGraphExternalConnectorsExternalGroup {
	if o == nil || o.Value == nil {
		var ret []MicrosoftGraphExternalConnectorsExternalGroup
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfExternalGroup) GetValueOk() (*[]MicrosoftGraphExternalConnectorsExternalGroup, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CollectionOfExternalGroup) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given []MicrosoftGraphExternalConnectorsExternalGroup and assigns it to the Value field.
func (o *CollectionOfExternalGroup) SetValue(v []MicrosoftGraphExternalConnectorsExternalGroup) {
	o.Value = &v
}

// GetOdataNextLink returns the OdataNextLink field value if set, zero value otherwise.
func (o *CollectionOfExternalGroup) GetOdataNextLink() string {
	if o == nil || o.OdataNextLink == nil {
		var ret string
		return ret
	}
	return *o.OdataNextLink
}

// GetOdataNextLinkOk returns a tuple with the OdataNextLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionOfExternalGroup) GetOdataNextLinkOk() (*string, bool) {
	if o == nil || o.OdataNextLink == nil {
		return nil, false
	}
	return o.OdataNextLink, true
}

// HasOdataNextLink returns a boolean if a field has been set.
func (o *CollectionOfExternalGroup) HasOdataNextLink() bool {
	if o != nil && o.OdataNextLink != nil {
		return true
	}

	return false
}

// SetOdataNextLink gets a reference to the given string and assigns it to the OdataNextLink field.
func (o *CollectionOfExternalGroup) SetOdataNextLink(v string) {
	o.OdataNextLink = &v
}

func (o CollectionOfExternalGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.OdataNextLink != nil {
		toSerialize["@odata.nextLink"] = o.OdataNextLink
	}
	return json.Marshal(toSerialize)
}

type NullableCollectionOfExternalGroup struct {
	value *CollectionOfExternalGroup
	isSet bool
}

func (v NullableCollectionOfExternalGroup) Get() *CollectionOfExternalGroup {
	return v.value
}

func (v *NullableCollectionOfExternalGroup) Set(val *CollectionOfExternalGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionOfExternalGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionOfExternalGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionOfExternalGroup(val *CollectionOfExternalGroup) *NullableCollectionOfExternalGroup {
	return &NullableCollectionOfExternalGroup{value: val, isSet: true}
}

func (v NullableCollectionOfExternalGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionOfExternalGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


