/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msgraph

import (
	"encoding/json"
)

// MicrosoftGraphDomainDnsRecord struct for MicrosoftGraphDomainDnsRecord
type MicrosoftGraphDomainDnsRecord struct {
	// Read-only.
	Id *string `json:"id,omitempty"`
	// If false, this record must be configured by the customer at the DNS host for Microsoft Online Services to operate correctly with the domain.
	IsOptional *bool `json:"isOptional,omitempty"`
	// Value used when configuring the name of the DNS record at the DNS host.
	Label *string `json:"label,omitempty"`
	// Indicates what type of DNS record this entity represents.The value can be one of the following: CName, Mx, Srv, TxtKey
	RecordType NullableString `json:"recordType,omitempty"`
	// Microsoft Online Service or feature that has a dependency on this DNS record.Can be one of the following values: null, Email, Sharepoint, EmailInternalRelayOnly, OfficeCommunicationsOnline, SharePointDefaultDomain, FullRedelegation, SharePointPublic, OrgIdAuthentication, Yammer, Intune
	SupportedService *string `json:"supportedService,omitempty"`
	// Value to use when configuring the time-to-live (ttl) property of the DNS record at the DNS host. Not nullable
	Ttl *int32 `json:"ttl,omitempty"`
}

// NewMicrosoftGraphDomainDnsRecord instantiates a new MicrosoftGraphDomainDnsRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMicrosoftGraphDomainDnsRecord() *MicrosoftGraphDomainDnsRecord {
	this := MicrosoftGraphDomainDnsRecord{}
	return &this
}

// NewMicrosoftGraphDomainDnsRecordWithDefaults instantiates a new MicrosoftGraphDomainDnsRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMicrosoftGraphDomainDnsRecordWithDefaults() *MicrosoftGraphDomainDnsRecord {
	this := MicrosoftGraphDomainDnsRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MicrosoftGraphDomainDnsRecord) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphDomainDnsRecord) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MicrosoftGraphDomainDnsRecord) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MicrosoftGraphDomainDnsRecord) SetId(v string) {
	o.Id = &v
}

// GetIsOptional returns the IsOptional field value if set, zero value otherwise.
func (o *MicrosoftGraphDomainDnsRecord) GetIsOptional() bool {
	if o == nil || o.IsOptional == nil {
		var ret bool
		return ret
	}
	return *o.IsOptional
}

// GetIsOptionalOk returns a tuple with the IsOptional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphDomainDnsRecord) GetIsOptionalOk() (*bool, bool) {
	if o == nil || o.IsOptional == nil {
		return nil, false
	}
	return o.IsOptional, true
}

// HasIsOptional returns a boolean if a field has been set.
func (o *MicrosoftGraphDomainDnsRecord) HasIsOptional() bool {
	if o != nil && o.IsOptional != nil {
		return true
	}

	return false
}

// SetIsOptional gets a reference to the given bool and assigns it to the IsOptional field.
func (o *MicrosoftGraphDomainDnsRecord) SetIsOptional(v bool) {
	o.IsOptional = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *MicrosoftGraphDomainDnsRecord) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphDomainDnsRecord) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *MicrosoftGraphDomainDnsRecord) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *MicrosoftGraphDomainDnsRecord) SetLabel(v string) {
	o.Label = &v
}

// GetRecordType returns the RecordType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphDomainDnsRecord) GetRecordType() string {
	if o == nil || o.RecordType.Get() == nil {
		var ret string
		return ret
	}
	return *o.RecordType.Get()
}

// GetRecordTypeOk returns a tuple with the RecordType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphDomainDnsRecord) GetRecordTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RecordType.Get(), o.RecordType.IsSet()
}

// HasRecordType returns a boolean if a field has been set.
func (o *MicrosoftGraphDomainDnsRecord) HasRecordType() bool {
	if o != nil && o.RecordType.IsSet() {
		return true
	}

	return false
}

// SetRecordType gets a reference to the given NullableString and assigns it to the RecordType field.
func (o *MicrosoftGraphDomainDnsRecord) SetRecordType(v string) {
	o.RecordType.Set(&v)
}
// SetRecordTypeNil sets the value for RecordType to be an explicit nil
func (o *MicrosoftGraphDomainDnsRecord) SetRecordTypeNil() {
	o.RecordType.Set(nil)
}

// UnsetRecordType ensures that no value is present for RecordType, not even an explicit nil
func (o *MicrosoftGraphDomainDnsRecord) UnsetRecordType() {
	o.RecordType.Unset()
}

// GetSupportedService returns the SupportedService field value if set, zero value otherwise.
func (o *MicrosoftGraphDomainDnsRecord) GetSupportedService() string {
	if o == nil || o.SupportedService == nil {
		var ret string
		return ret
	}
	return *o.SupportedService
}

// GetSupportedServiceOk returns a tuple with the SupportedService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphDomainDnsRecord) GetSupportedServiceOk() (*string, bool) {
	if o == nil || o.SupportedService == nil {
		return nil, false
	}
	return o.SupportedService, true
}

// HasSupportedService returns a boolean if a field has been set.
func (o *MicrosoftGraphDomainDnsRecord) HasSupportedService() bool {
	if o != nil && o.SupportedService != nil {
		return true
	}

	return false
}

// SetSupportedService gets a reference to the given string and assigns it to the SupportedService field.
func (o *MicrosoftGraphDomainDnsRecord) SetSupportedService(v string) {
	o.SupportedService = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *MicrosoftGraphDomainDnsRecord) GetTtl() int32 {
	if o == nil || o.Ttl == nil {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrosoftGraphDomainDnsRecord) GetTtlOk() (*int32, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *MicrosoftGraphDomainDnsRecord) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *MicrosoftGraphDomainDnsRecord) SetTtl(v int32) {
	o.Ttl = &v
}

func (o MicrosoftGraphDomainDnsRecord) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.IsOptional != nil {
		toSerialize["isOptional"] = o.IsOptional
	}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	if o.RecordType.IsSet() {
		toSerialize["recordType"] = o.RecordType.Get()
	}
	if o.SupportedService != nil {
		toSerialize["supportedService"] = o.SupportedService
	}
	if o.Ttl != nil {
		toSerialize["ttl"] = o.Ttl
	}
	return json.Marshal(toSerialize)
}

type NullableMicrosoftGraphDomainDnsRecord struct {
	value *MicrosoftGraphDomainDnsRecord
	isSet bool
}

func (v NullableMicrosoftGraphDomainDnsRecord) Get() *MicrosoftGraphDomainDnsRecord {
	return v.value
}

func (v *NullableMicrosoftGraphDomainDnsRecord) Set(val *MicrosoftGraphDomainDnsRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableMicrosoftGraphDomainDnsRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableMicrosoftGraphDomainDnsRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMicrosoftGraphDomainDnsRecord(val *MicrosoftGraphDomainDnsRecord) *NullableMicrosoftGraphDomainDnsRecord {
	return &NullableMicrosoftGraphDomainDnsRecord{value: val, isSet: true}
}

func (v NullableMicrosoftGraphDomainDnsRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMicrosoftGraphDomainDnsRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


