/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AdminConsentRequestPolicy struct for AdminConsentRequestPolicy
type AdminConsentRequestPolicy struct {
	// Specifies whether the admin consent request feature is enabled or disabled. Required.
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// Specifies whether reviewers will receive notifications. Required.
	NotifyReviewers *bool `json:"notifyReviewers,omitempty"`
	// Specifies whether reviewers will receive reminder emails. Required.
	RemindersEnabled *bool `json:"remindersEnabled,omitempty"`
	// Specifies the duration the request is active before it automatically expires if no decision is applied.
	RequestDurationInDays *int32 `json:"requestDurationInDays,omitempty"`
	// The list of reviewers for the admin consent. Required.
	Reviewers *[]*AnyOfmicrosoftGraphAccessReviewReviewerScope `json:"reviewers,omitempty"`
	// Specifies the version of this policy. When the policy is updated, this version is updated. Read-only.
	Version *int32 `json:"version,omitempty"`
}

// NewAdminConsentRequestPolicy instantiates a new AdminConsentRequestPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminConsentRequestPolicy() *AdminConsentRequestPolicy {
	this := AdminConsentRequestPolicy{}
	return &this
}

// NewAdminConsentRequestPolicyWithDefaults instantiates a new AdminConsentRequestPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminConsentRequestPolicyWithDefaults() *AdminConsentRequestPolicy {
	this := AdminConsentRequestPolicy{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *AdminConsentRequestPolicy) GetIsEnabled() bool {
	if o == nil || o.IsEnabled == nil {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminConsentRequestPolicy) GetIsEnabledOk() (*bool, bool) {
	if o == nil || o.IsEnabled == nil {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *AdminConsentRequestPolicy) HasIsEnabled() bool {
	if o != nil && o.IsEnabled != nil {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *AdminConsentRequestPolicy) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetNotifyReviewers returns the NotifyReviewers field value if set, zero value otherwise.
func (o *AdminConsentRequestPolicy) GetNotifyReviewers() bool {
	if o == nil || o.NotifyReviewers == nil {
		var ret bool
		return ret
	}
	return *o.NotifyReviewers
}

// GetNotifyReviewersOk returns a tuple with the NotifyReviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminConsentRequestPolicy) GetNotifyReviewersOk() (*bool, bool) {
	if o == nil || o.NotifyReviewers == nil {
		return nil, false
	}
	return o.NotifyReviewers, true
}

// HasNotifyReviewers returns a boolean if a field has been set.
func (o *AdminConsentRequestPolicy) HasNotifyReviewers() bool {
	if o != nil && o.NotifyReviewers != nil {
		return true
	}

	return false
}

// SetNotifyReviewers gets a reference to the given bool and assigns it to the NotifyReviewers field.
func (o *AdminConsentRequestPolicy) SetNotifyReviewers(v bool) {
	o.NotifyReviewers = &v
}

// GetRemindersEnabled returns the RemindersEnabled field value if set, zero value otherwise.
func (o *AdminConsentRequestPolicy) GetRemindersEnabled() bool {
	if o == nil || o.RemindersEnabled == nil {
		var ret bool
		return ret
	}
	return *o.RemindersEnabled
}

// GetRemindersEnabledOk returns a tuple with the RemindersEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminConsentRequestPolicy) GetRemindersEnabledOk() (*bool, bool) {
	if o == nil || o.RemindersEnabled == nil {
		return nil, false
	}
	return o.RemindersEnabled, true
}

// HasRemindersEnabled returns a boolean if a field has been set.
func (o *AdminConsentRequestPolicy) HasRemindersEnabled() bool {
	if o != nil && o.RemindersEnabled != nil {
		return true
	}

	return false
}

// SetRemindersEnabled gets a reference to the given bool and assigns it to the RemindersEnabled field.
func (o *AdminConsentRequestPolicy) SetRemindersEnabled(v bool) {
	o.RemindersEnabled = &v
}

// GetRequestDurationInDays returns the RequestDurationInDays field value if set, zero value otherwise.
func (o *AdminConsentRequestPolicy) GetRequestDurationInDays() int32 {
	if o == nil || o.RequestDurationInDays == nil {
		var ret int32
		return ret
	}
	return *o.RequestDurationInDays
}

// GetRequestDurationInDaysOk returns a tuple with the RequestDurationInDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminConsentRequestPolicy) GetRequestDurationInDaysOk() (*int32, bool) {
	if o == nil || o.RequestDurationInDays == nil {
		return nil, false
	}
	return o.RequestDurationInDays, true
}

// HasRequestDurationInDays returns a boolean if a field has been set.
func (o *AdminConsentRequestPolicy) HasRequestDurationInDays() bool {
	if o != nil && o.RequestDurationInDays != nil {
		return true
	}

	return false
}

// SetRequestDurationInDays gets a reference to the given int32 and assigns it to the RequestDurationInDays field.
func (o *AdminConsentRequestPolicy) SetRequestDurationInDays(v int32) {
	o.RequestDurationInDays = &v
}

// GetReviewers returns the Reviewers field value if set, zero value otherwise.
func (o *AdminConsentRequestPolicy) GetReviewers() []*AnyOfmicrosoftGraphAccessReviewReviewerScope {
	if o == nil || o.Reviewers == nil {
		var ret []*AnyOfmicrosoftGraphAccessReviewReviewerScope
		return ret
	}
	return *o.Reviewers
}

// GetReviewersOk returns a tuple with the Reviewers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminConsentRequestPolicy) GetReviewersOk() (*[]*AnyOfmicrosoftGraphAccessReviewReviewerScope, bool) {
	if o == nil || o.Reviewers == nil {
		return nil, false
	}
	return o.Reviewers, true
}

// HasReviewers returns a boolean if a field has been set.
func (o *AdminConsentRequestPolicy) HasReviewers() bool {
	if o != nil && o.Reviewers != nil {
		return true
	}

	return false
}

// SetReviewers gets a reference to the given []*AnyOfmicrosoftGraphAccessReviewReviewerScope and assigns it to the Reviewers field.
func (o *AdminConsentRequestPolicy) SetReviewers(v []*AnyOfmicrosoftGraphAccessReviewReviewerScope) {
	o.Reviewers = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AdminConsentRequestPolicy) GetVersion() int32 {
	if o == nil || o.Version == nil {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminConsentRequestPolicy) GetVersionOk() (*int32, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AdminConsentRequestPolicy) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *AdminConsentRequestPolicy) SetVersion(v int32) {
	o.Version = &v
}

func (o AdminConsentRequestPolicy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IsEnabled != nil {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	if o.NotifyReviewers != nil {
		toSerialize["notifyReviewers"] = o.NotifyReviewers
	}
	if o.RemindersEnabled != nil {
		toSerialize["remindersEnabled"] = o.RemindersEnabled
	}
	if o.RequestDurationInDays != nil {
		toSerialize["requestDurationInDays"] = o.RequestDurationInDays
	}
	if o.Reviewers != nil {
		toSerialize["reviewers"] = o.Reviewers
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableAdminConsentRequestPolicy struct {
	value *AdminConsentRequestPolicy
	isSet bool
}

func (v NullableAdminConsentRequestPolicy) Get() *AdminConsentRequestPolicy {
	return v.value
}

func (v *NullableAdminConsentRequestPolicy) Set(val *AdminConsentRequestPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminConsentRequestPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminConsentRequestPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminConsentRequestPolicy(val *AdminConsentRequestPolicy) *NullableAdminConsentRequestPolicy {
	return &NullableAdminConsentRequestPolicy{value: val, isSet: true}
}

func (v NullableAdminConsentRequestPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminConsentRequestPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


