/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msgraph

import (
	"encoding/json"
)

// InlineObject1488 struct for InlineObject1488
type InlineObject1488 struct {
	Text AnyOfobject `json:"text,omitempty"`
	NumBytes AnyOfobject `json:"numBytes,omitempty"`
}

// NewInlineObject1488 instantiates a new InlineObject1488 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject1488() *InlineObject1488 {
	this := InlineObject1488{}
	return &this
}

// NewInlineObject1488WithDefaults instantiates a new InlineObject1488 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject1488WithDefaults() *InlineObject1488 {
	this := InlineObject1488{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InlineObject1488) GetText() AnyOfobject {
	if o == nil  {
		var ret AnyOfobject
		return ret
	}
	return o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject1488) GetTextOk() (*AnyOfobject, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return &o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *InlineObject1488) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given AnyOfobject and assigns it to the Text field.
func (o *InlineObject1488) SetText(v AnyOfobject) {
	o.Text = v
}

// GetNumBytes returns the NumBytes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InlineObject1488) GetNumBytes() AnyOfobject {
	if o == nil  {
		var ret AnyOfobject
		return ret
	}
	return o.NumBytes
}

// GetNumBytesOk returns a tuple with the NumBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject1488) GetNumBytesOk() (*AnyOfobject, bool) {
	if o == nil || o.NumBytes == nil {
		return nil, false
	}
	return &o.NumBytes, true
}

// HasNumBytes returns a boolean if a field has been set.
func (o *InlineObject1488) HasNumBytes() bool {
	if o != nil && o.NumBytes != nil {
		return true
	}

	return false
}

// SetNumBytes gets a reference to the given AnyOfobject and assigns it to the NumBytes field.
func (o *InlineObject1488) SetNumBytes(v AnyOfobject) {
	o.NumBytes = v
}

func (o InlineObject1488) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	if o.NumBytes != nil {
		toSerialize["numBytes"] = o.NumBytes
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject1488 struct {
	value *InlineObject1488
	isSet bool
}

func (v NullableInlineObject1488) Get() *InlineObject1488 {
	return v.value
}

func (v *NullableInlineObject1488) Set(val *InlineObject1488) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1488) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1488) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1488(val *InlineObject1488) *NullableInlineObject1488 {
	return &NullableInlineObject1488{value: val, isSet: true}
}

func (v NullableInlineObject1488) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1488) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


