/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MicrosoftGraphConditionalAccessSessionControls struct for MicrosoftGraphConditionalAccessSessionControls
type MicrosoftGraphConditionalAccessSessionControls struct {
	// Session control to enforce application restrictions. Only Exchange Online and Sharepoint Online support this session control.
	ApplicationEnforcedRestrictions AnyOfmicrosoftGraphApplicationEnforcedRestrictionsSessionControl `json:"applicationEnforcedRestrictions,omitempty"`
	// Session control to apply cloud app security.
	CloudAppSecurity AnyOfmicrosoftGraphCloudAppSecuritySessionControl `json:"cloudAppSecurity,omitempty"`
	// Session control to define whether to persist cookies or not. All apps should be selected for this session control to work correctly.
	PersistentBrowser AnyOfmicrosoftGraphPersistentBrowserSessionControl `json:"persistentBrowser,omitempty"`
	// Session control to enforce signin frequency.
	SignInFrequency AnyOfmicrosoftGraphSignInFrequencySessionControl `json:"signInFrequency,omitempty"`
}

// NewMicrosoftGraphConditionalAccessSessionControls instantiates a new MicrosoftGraphConditionalAccessSessionControls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMicrosoftGraphConditionalAccessSessionControls() *MicrosoftGraphConditionalAccessSessionControls {
	this := MicrosoftGraphConditionalAccessSessionControls{}
	return &this
}

// NewMicrosoftGraphConditionalAccessSessionControlsWithDefaults instantiates a new MicrosoftGraphConditionalAccessSessionControls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMicrosoftGraphConditionalAccessSessionControlsWithDefaults() *MicrosoftGraphConditionalAccessSessionControls {
	this := MicrosoftGraphConditionalAccessSessionControls{}
	return &this
}

// GetApplicationEnforcedRestrictions returns the ApplicationEnforcedRestrictions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphConditionalAccessSessionControls) GetApplicationEnforcedRestrictions() AnyOfmicrosoftGraphApplicationEnforcedRestrictionsSessionControl {
	if o == nil  {
		var ret AnyOfmicrosoftGraphApplicationEnforcedRestrictionsSessionControl
		return ret
	}
	return o.ApplicationEnforcedRestrictions
}

// GetApplicationEnforcedRestrictionsOk returns a tuple with the ApplicationEnforcedRestrictions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphConditionalAccessSessionControls) GetApplicationEnforcedRestrictionsOk() (*AnyOfmicrosoftGraphApplicationEnforcedRestrictionsSessionControl, bool) {
	if o == nil || o.ApplicationEnforcedRestrictions == nil {
		return nil, false
	}
	return &o.ApplicationEnforcedRestrictions, true
}

// HasApplicationEnforcedRestrictions returns a boolean if a field has been set.
func (o *MicrosoftGraphConditionalAccessSessionControls) HasApplicationEnforcedRestrictions() bool {
	if o != nil && o.ApplicationEnforcedRestrictions != nil {
		return true
	}

	return false
}

// SetApplicationEnforcedRestrictions gets a reference to the given AnyOfmicrosoftGraphApplicationEnforcedRestrictionsSessionControl and assigns it to the ApplicationEnforcedRestrictions field.
func (o *MicrosoftGraphConditionalAccessSessionControls) SetApplicationEnforcedRestrictions(v AnyOfmicrosoftGraphApplicationEnforcedRestrictionsSessionControl) {
	o.ApplicationEnforcedRestrictions = v
}

// GetCloudAppSecurity returns the CloudAppSecurity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphConditionalAccessSessionControls) GetCloudAppSecurity() AnyOfmicrosoftGraphCloudAppSecuritySessionControl {
	if o == nil  {
		var ret AnyOfmicrosoftGraphCloudAppSecuritySessionControl
		return ret
	}
	return o.CloudAppSecurity
}

// GetCloudAppSecurityOk returns a tuple with the CloudAppSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphConditionalAccessSessionControls) GetCloudAppSecurityOk() (*AnyOfmicrosoftGraphCloudAppSecuritySessionControl, bool) {
	if o == nil || o.CloudAppSecurity == nil {
		return nil, false
	}
	return &o.CloudAppSecurity, true
}

// HasCloudAppSecurity returns a boolean if a field has been set.
func (o *MicrosoftGraphConditionalAccessSessionControls) HasCloudAppSecurity() bool {
	if o != nil && o.CloudAppSecurity != nil {
		return true
	}

	return false
}

// SetCloudAppSecurity gets a reference to the given AnyOfmicrosoftGraphCloudAppSecuritySessionControl and assigns it to the CloudAppSecurity field.
func (o *MicrosoftGraphConditionalAccessSessionControls) SetCloudAppSecurity(v AnyOfmicrosoftGraphCloudAppSecuritySessionControl) {
	o.CloudAppSecurity = v
}

// GetPersistentBrowser returns the PersistentBrowser field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphConditionalAccessSessionControls) GetPersistentBrowser() AnyOfmicrosoftGraphPersistentBrowserSessionControl {
	if o == nil  {
		var ret AnyOfmicrosoftGraphPersistentBrowserSessionControl
		return ret
	}
	return o.PersistentBrowser
}

// GetPersistentBrowserOk returns a tuple with the PersistentBrowser field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphConditionalAccessSessionControls) GetPersistentBrowserOk() (*AnyOfmicrosoftGraphPersistentBrowserSessionControl, bool) {
	if o == nil || o.PersistentBrowser == nil {
		return nil, false
	}
	return &o.PersistentBrowser, true
}

// HasPersistentBrowser returns a boolean if a field has been set.
func (o *MicrosoftGraphConditionalAccessSessionControls) HasPersistentBrowser() bool {
	if o != nil && o.PersistentBrowser != nil {
		return true
	}

	return false
}

// SetPersistentBrowser gets a reference to the given AnyOfmicrosoftGraphPersistentBrowserSessionControl and assigns it to the PersistentBrowser field.
func (o *MicrosoftGraphConditionalAccessSessionControls) SetPersistentBrowser(v AnyOfmicrosoftGraphPersistentBrowserSessionControl) {
	o.PersistentBrowser = v
}

// GetSignInFrequency returns the SignInFrequency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MicrosoftGraphConditionalAccessSessionControls) GetSignInFrequency() AnyOfmicrosoftGraphSignInFrequencySessionControl {
	if o == nil  {
		var ret AnyOfmicrosoftGraphSignInFrequencySessionControl
		return ret
	}
	return o.SignInFrequency
}

// GetSignInFrequencyOk returns a tuple with the SignInFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MicrosoftGraphConditionalAccessSessionControls) GetSignInFrequencyOk() (*AnyOfmicrosoftGraphSignInFrequencySessionControl, bool) {
	if o == nil || o.SignInFrequency == nil {
		return nil, false
	}
	return &o.SignInFrequency, true
}

// HasSignInFrequency returns a boolean if a field has been set.
func (o *MicrosoftGraphConditionalAccessSessionControls) HasSignInFrequency() bool {
	if o != nil && o.SignInFrequency != nil {
		return true
	}

	return false
}

// SetSignInFrequency gets a reference to the given AnyOfmicrosoftGraphSignInFrequencySessionControl and assigns it to the SignInFrequency field.
func (o *MicrosoftGraphConditionalAccessSessionControls) SetSignInFrequency(v AnyOfmicrosoftGraphSignInFrequencySessionControl) {
	o.SignInFrequency = v
}

func (o MicrosoftGraphConditionalAccessSessionControls) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApplicationEnforcedRestrictions != nil {
		toSerialize["applicationEnforcedRestrictions"] = o.ApplicationEnforcedRestrictions
	}
	if o.CloudAppSecurity != nil {
		toSerialize["cloudAppSecurity"] = o.CloudAppSecurity
	}
	if o.PersistentBrowser != nil {
		toSerialize["persistentBrowser"] = o.PersistentBrowser
	}
	if o.SignInFrequency != nil {
		toSerialize["signInFrequency"] = o.SignInFrequency
	}
	return json.Marshal(toSerialize)
}

type NullableMicrosoftGraphConditionalAccessSessionControls struct {
	value *MicrosoftGraphConditionalAccessSessionControls
	isSet bool
}

func (v NullableMicrosoftGraphConditionalAccessSessionControls) Get() *MicrosoftGraphConditionalAccessSessionControls {
	return v.value
}

func (v *NullableMicrosoftGraphConditionalAccessSessionControls) Set(val *MicrosoftGraphConditionalAccessSessionControls) {
	v.value = val
	v.isSet = true
}

func (v NullableMicrosoftGraphConditionalAccessSessionControls) IsSet() bool {
	return v.isSet
}

func (v *NullableMicrosoftGraphConditionalAccessSessionControls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMicrosoftGraphConditionalAccessSessionControls(val *MicrosoftGraphConditionalAccessSessionControls) *NullableMicrosoftGraphConditionalAccessSessionControls {
	return &NullableMicrosoftGraphConditionalAccessSessionControls{value: val, isSet: true}
}

func (v NullableMicrosoftGraphConditionalAccessSessionControls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMicrosoftGraphConditionalAccessSessionControls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


