/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ColumnLink struct for ColumnLink
type ColumnLink struct {
	// The name of the column  in this content type.
	Name NullableString `json:"name,omitempty"`
}

// NewColumnLink instantiates a new ColumnLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColumnLink() *ColumnLink {
	this := ColumnLink{}
	return &this
}

// NewColumnLinkWithDefaults instantiates a new ColumnLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColumnLinkWithDefaults() *ColumnLink {
	this := ColumnLink{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ColumnLink) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ColumnLink) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ColumnLink) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ColumnLink) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ColumnLink) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ColumnLink) UnsetName() {
	o.Name.Unset()
}

func (o ColumnLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableColumnLink struct {
	value *ColumnLink
	isSet bool
}

func (v NullableColumnLink) Get() *ColumnLink {
	return v.value
}

func (v *NullableColumnLink) Set(val *ColumnLink) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnLink) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnLink(val *ColumnLink) *NullableColumnLink {
	return &NullableColumnLink{value: val, isSet: true}
}

func (v NullableColumnLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


