/*
Partial Graph API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package msgraph

import (
	"encoding/json"
)

// InlineObject1251 struct for InlineObject1251
type InlineObject1251 struct {
	X AnyOfobject `json:"x,omitempty"`
	DegFreedom AnyOfobject `json:"degFreedom,omitempty"`
	Cumulative AnyOfobject `json:"cumulative,omitempty"`
}

// NewInlineObject1251 instantiates a new InlineObject1251 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject1251() *InlineObject1251 {
	this := InlineObject1251{}
	return &this
}

// NewInlineObject1251WithDefaults instantiates a new InlineObject1251 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject1251WithDefaults() *InlineObject1251 {
	this := InlineObject1251{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InlineObject1251) GetX() AnyOfobject {
	if o == nil  {
		var ret AnyOfobject
		return ret
	}
	return o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject1251) GetXOk() (*AnyOfobject, bool) {
	if o == nil || o.X == nil {
		return nil, false
	}
	return &o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *InlineObject1251) HasX() bool {
	if o != nil && o.X != nil {
		return true
	}

	return false
}

// SetX gets a reference to the given AnyOfobject and assigns it to the X field.
func (o *InlineObject1251) SetX(v AnyOfobject) {
	o.X = v
}

// GetDegFreedom returns the DegFreedom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InlineObject1251) GetDegFreedom() AnyOfobject {
	if o == nil  {
		var ret AnyOfobject
		return ret
	}
	return o.DegFreedom
}

// GetDegFreedomOk returns a tuple with the DegFreedom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject1251) GetDegFreedomOk() (*AnyOfobject, bool) {
	if o == nil || o.DegFreedom == nil {
		return nil, false
	}
	return &o.DegFreedom, true
}

// HasDegFreedom returns a boolean if a field has been set.
func (o *InlineObject1251) HasDegFreedom() bool {
	if o != nil && o.DegFreedom != nil {
		return true
	}

	return false
}

// SetDegFreedom gets a reference to the given AnyOfobject and assigns it to the DegFreedom field.
func (o *InlineObject1251) SetDegFreedom(v AnyOfobject) {
	o.DegFreedom = v
}

// GetCumulative returns the Cumulative field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InlineObject1251) GetCumulative() AnyOfobject {
	if o == nil  {
		var ret AnyOfobject
		return ret
	}
	return o.Cumulative
}

// GetCumulativeOk returns a tuple with the Cumulative field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject1251) GetCumulativeOk() (*AnyOfobject, bool) {
	if o == nil || o.Cumulative == nil {
		return nil, false
	}
	return &o.Cumulative, true
}

// HasCumulative returns a boolean if a field has been set.
func (o *InlineObject1251) HasCumulative() bool {
	if o != nil && o.Cumulative != nil {
		return true
	}

	return false
}

// SetCumulative gets a reference to the given AnyOfobject and assigns it to the Cumulative field.
func (o *InlineObject1251) SetCumulative(v AnyOfobject) {
	o.Cumulative = v
}

func (o InlineObject1251) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.X != nil {
		toSerialize["x"] = o.X
	}
	if o.DegFreedom != nil {
		toSerialize["degFreedom"] = o.DegFreedom
	}
	if o.Cumulative != nil {
		toSerialize["cumulative"] = o.Cumulative
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject1251 struct {
	value *InlineObject1251
	isSet bool
}

func (v NullableInlineObject1251) Get() *InlineObject1251 {
	return v.value
}

func (v *NullableInlineObject1251) Set(val *InlineObject1251) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1251) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1251) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1251(val *InlineObject1251) *NullableInlineObject1251 {
	return &NullableInlineObject1251{value: val, isSet: true}
}

func (v NullableInlineObject1251) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1251) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


